cfg:
  base_momentum: 0.85
  batch_size: 4
  bbox_label_path: /home/vrb230004/CombinedModels/labels
  centerpoint:
    code_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.2
    - 0.2
    - 1.0
    - 1.0
    common_heads:
      dim:
      - 3
      - 2
      height:
      - 1
      - 2
      reg:
      - 2
      - 2
      rot:
      - 2
      - 2
      vel:
      - 2
      - 2
    dataset: nuscenes
    dcn_head: false
    in_channels:
    - 128
    share_conv_channel: 64
    tasks:
    - class_names:
      - car
      num_class: 1
    - class_names:
      - truck
      - construction vehicle
      num_class: 2
    - class_names:
      - bus
      - trailer
      num_class: 2
    - class_names:
      - barrier
      num_class: 1
    - class_names:
      - motorcycle
      - bicycle
      num_class: 2
    - class_names:
      - pedestrian
      - traffic cone
      num_class: 2
    weight: 0.25
  ckpt_path: /home/vrb230004/CombinedModels/lightning_logs/version_0/checkpoints/epoch=28-step=25462.ckpt
  cvt_metadata_path: /home/vrb230004/media/datasets/cvt_labels_nuscenes
  dataset_dir: /home/vrb230004/media/datasets/nuscenes
  devices:
  - 0
  - 1
  - 2
  - 3
  epochs: 30
  log_dir: /home/vrb230004/CombinedModels/logs
  lr: 0.001
  max_momentum: 0.95
  num_workers: 8
  resize_shape:
  - 128
  - 128
  test:
    ckpt_path: /home/vrb230004/CombinedModels/lightning_logs/version_0/checkpoints/epoch=28-step=25462.ckpt
    max_per_img: 500
    nms:
      nms_iou_threshold: 0.2
      nms_post_max_size: 83
      nms_pre_max_size: 1000
    out_size_factor: 4
    pc_range:
    - -51.2
    - -51.2
    post_center_limit_range:
    - -61.2
    - -61.2
    - -10.0
    - 61.2
    - 61.2
    - 10.0
    score_threshold: 0.1
    voxel_size:
    - 0.2
    - 0.2
  weight_decay: 0.01
resize_shape: !!python/tuple
- 128
- 128
